### ISSUE TITLE
Support "link phrase at point"

### ISSUE THREAD

**Issue by naclander** [Benaiah/org-wikish#1]
Often times I want to create new wiki entries from phrases, not just words.

Currently, org-wikish supports `org-wikish-link-word-at-point` but I think this should be extended to `org-wikish-link-phrase-at-point` where a phrase might be the current region?

Is this a feature that you think is feasible/reasonable/useful?

**Comment by Benaiah** [comment]
Closed in https://github.com/Benaiah/org-wikish/commit/ab5302997c640a1fb7ed3a5e7fac398cdae24aa1 - thanks for the feature suggestion! The new function is called `org-wikish-link-region`.

**Comment by naclander** [comment]
@Benaiah cool! You probably want to update the wiki as well with this new command.

**Comment by naclander** [comment]
@Benaiah I just got aroudn to testing this.

Unlike `org-wikish-link-word-at-point `, which automatically creates a new wiki page with the name of the word under the point, `org-wikish-link-region` doesn't automatically creates a wiki page, but instead prompts me to either create a new name, or use an existing wiki page.

In my opinion, the two mentioned functions above shouldn't be that different.

In my opinion, `org-wikish-link-region` should either:

1) Prompt the user to create a new wiki page with the current region as the proposed name for the page, but let the user change it. This is almost what happens currently, but I have to retype the region I selected as the page name, which might lead to errors
2) Automatically create the page just like with `org-wikish-link-word-at-point` without prompting the user for anything.

I think I prefer 1), as it seems more user friendly. But I definitely don't like the current system which requires me to re-type the region content I just highlighted, if I want my page to be named after that region content. Makes sense?

What do you think?
